### ISSUE TITLE
Do you store your cassetes on Git/Mercurial? whats the best practice

### ISSUE THREAD

**Issue by ialex** [kevin1024/vcrpy#160]
I wanted to know what you guys do if you store your cassetes on Git/Mercurial or is it better to let every dev to build their own cassetes when they run the test?

Does having them on a CVS helps the CI server or not?

**Comment by IvanMalison** [comment]
> I wanted to know what you guys do if you store your cassetes on Git/Mercurial or is it better to let every dev to build their own cassetes when they run the test?

The answer to this question probably depends a bit on your particular use case, but in general, I would say that it probably IS a good idea to store cassettes in version control. If you are worried about polluting the repository/git history you could store the cassettes in a separate module and either
a) use a submodule
b) have people manually clone the repository and put it in the right place

Devs having their own cassettes is probably not a good idea in most situations. Doing this would make it harder to track down the source of problems when they arise, and it would increase the setup people need to do to get things running.

Imagine a dev working in an SOA that uses vcrpy. They would have to set up all the services that the service they are testing interacts with in order to get their cassettes.

> 
> Does having them on a CVS helps the CI server or not?

Of course it would. If they aren't in version control or somehow accessible to the CI server what is the point of even using vcrpy at all. At that point it would just be running the tests as if vcrpy weren't used at all.
