### ISSUE TITLE
Upload-like requests where body.read() doesn't return the full file (i.e. it returns small buffers) hang VCRpy

### ISSUE THREAD

**Issue by raff** [kevin1024/vcrpy#218]
If the request "body" is a file-like object where body.read() doesn't return the full file (i.e. I am testing a proxy where "body" is actually a socket that reads from the client and body.read() return fixed length buffers), the request hangs when running through VCRpy.

The problem is here (vcrpy/request.py: **init**):

```
    self._was_file = hasattr(body, 'read')
    if self._was_file:
        self.body = body.read()
```

where you do a single read. The request to the real server probably hangs because the Content-Length specify the full size of the file, but the posted body is shorter (so the server is waiting for more bytes, while the client is waiting for the response).

The correct solution should be to keep self.body as something the request can "read from", but a working solution, easier to implement, could be to at least do a "loop" of reads:

  while True:
    ret = body.read()
    if ret == '':
       break
    self.body += ret

**Comment by IvanMalison** [comment]
> The correct solution should be to keep self.body as something the request can "read from"

This is implemented in the way that it is to avoid having something like that, because such a thing can not be read from twice, and vcrpy must be able to read the body multiple times.

Your suggestion is probably the correct behavior, although this could result in a lot of data being loaded into memory.

**Comment by raff** [comment]
Yes, but it would be exactly the same amount of data read from a real file of the same total size. Thanks!

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
