### ISSUE TITLE
VCR Not Sending Client Certificate when wrapping Requests

### ISSUE THREAD

**Issue by fxfitz** [kevin1024/vcrpy#220]
When using VCR and attempting to send a client certificate to a webserver (as seen below), VCR does not include the certificate in the packets being sent out.

This can be confirmed by looking at a Wireshark capture ([screenshot](https://cloud.githubusercontent.com/assets/6355826/10439314/bc39db6e-70fe-11e5-9cef-7f53a95fe500.png)).  When the client presents the certificate, you can see the 'Certificates Length' is actually 0.

This works as expected when not using VCR.

``` python
creds_resp = requests.get(computer.creds_href,
                              cert=client_cert,
                              verify=CA_FILENAME)
```

**Comment by IvanMalison** [comment]
Seems likely that this is because we only forward certain values explicitly to the actual connection.

https://github.com/kevin1024/vcrpy/blob/2ac3fa9abe194141346806ced56b5e399ae96ec9/vcr/stubs/__init__.py#L176
https://github.com/kevin1024/vcrpy/blob/2ac3fa9abe194141346806ced56b5e399ae96ec9/vcr/stubs/__init__.py#L251

We probably need to store the data coming in as args, kwargs there and pass it on appropriately.

**Comment by agriffis** [comment]
@fxfitz You didn't happen to investigate this any further, did you?

**Comment by fxfitz** [comment]
Sadly, no, I haven't.

**Comment by kevin1024** [comment]
I'd like to write a test for this, but since this happens at the protocol layer I'm not sure how to assert that the certificate is included.

**Comment by kevin1024** [comment]
The SSL also changed in py2.7+ to use SSLContext instead of as args to the HTTPConnection object.  So this might be version-dependent.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
