### ISSUE TITLE
Decoding json body fails on DELETE request 

### ISSUE THREAD

**Issue by dz0ny** [kevin1024/vcrpy#231]
When `DELETE /some/uri` and response header contains `Content-Type: [application/json]` the response handler will try to decode empty body.

quick fix

```
# vcrpy/vcr/matchers.py
def _transform_json(body):
    # Request body is always a byte string, but json.loads() wants a text
    # string. RFC 7159 says the default encoding is UTF-8 (although UTF-16
    # and UTF-32 are also allowed: hmmmmm).
    if body:
        return json.loads(body.decode('utf-8'))
```

But this should be handled for other "transformers" as well, so maybe check for empty body in body method.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
