### ISSUE TITLE
improve documentation/checks -- e.g. can supply bogus record_mode

### ISSUE THREAD

**Issue by yarikoptic** [kevin1024/vcrpy#233]
I didn't find anywhere clear description of which record_mode's are supported. Moreover, providing some bogus value "worked" just fine (I guess as in 'all' mode)

**Comment by yarikoptic** [comment]
sorry, actually worked as 'once' ;-)

**Comment by IvanMalison** [comment]
see #208 . This is a known issue but we plan to fix it.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
