### ISSUE TITLE
With Python 3, the body of POST requests is base64-encoded

### ISSUE THREAD

**Issue by abompard** [kevin1024/vcrpy#241]
As a consequence of commit 09b7ccf (more precisely, of the conversion in the request body setter), the body of the POST requests are unreadable in the tape file:

``` patch
--- tape.yaml
+++ tape.yaml
@@ -41,8 +41,7 @@ interactions:
       content-type: [application/json; charset=utf-8]
     status: {code: 200, message: OK}
 - request:
-    body: mail_host=example.com
+    body: !!binary |
+      bWFpbF9ob3N0PWV4YW1wbGUuY29t
     headers:
       accept-encoding: ['gzip, deflate']
       content-type: [application/x-www-form-urlencoded]
```

It makes it much harder to diff changes between tapes committed in a VCS, and to identify what each request is coming from in the code.

**Comment by kevin1024** [comment]
Ugh yeah this is a problem.  I would prefer the cassette to be human readable if possible.  Would merge a pr to fix this.

**Comment by abompard** [comment]
@gward was the author of the commit, I can work on this but I'd be very happy to have his opinion on the matter.

**Comment by IvanMalison** [comment]
in my view, this is actually more of a problem with the yaml encoder than anything else. The problem is basically that in python 3, there is technically no way to directly represent a string in a serialized way. Python 3 strings can use several different in memory representations (see https://www.python.org/dev/peps/pep-0393/)

So basically @gward s change is an improvement because it makes explicit how the unicode string is serialized. The problem is that in python 3, the string is then encoded as a byte string which has this (non human readable representation) when it is serialized as yaml.

I may not be groking all of this correctly, and it may be that something else is going on, but i think that we would have to fix this in the serializer, rather than by changing what @gward did which was the right thing.

**Comment by IvanMalison** [comment]
[This comment](https://github.com/kevin1024/vcrpy/blob/43b3411e6c07d2d0fae9e4524082927179654a36/vcr/serialize.py#L13) seems relevant to @kevin1024 original intentions, and I think it might be false at this point because of @gward 's change.

**Comment by IvanMalison** [comment]
@kevin1024 I think that the concern of what yaml does should be separate from the general process of serialization.

I would argue that the RIGHT thing to do would be to pass non unicode string data to the serializer.

IF in the case of yaml, we actually want to serialize using a unicode string, we should convert that serialized string BACK to a python unicode string, and then let the yaml serializer serialize that.

This will allow us to have correct behavior for all serializers.

**Comment by IvanMalison** [comment]
@kevin1024 can you close or comment?

**Comment by kevin1024** [comment]
@IvanMalison Sorry, I'm a bit dense/confused so you might have to catch me up :)

> I would argue that the RIGHT thing to do would be to pass non unicode string data to the serializer.

I think in general, unicode is supposed to be a canonical, in-memory representation.  When you read or write it to disk/network, you need to encode it.

So shouldn't the utf-8 encoding happen at the boundary of the system, right before sending it to disk?  Read bytes -> decode ->  unicode -> process -> unicode -> encode -> write bytes

That said, this is all super philosophical and my main goal is to have human-readable cassettes.

**Comment by kevin1024** [comment]
I just read that [linked comment](https://github.com/kevin1024/vcrpy/blob/43b3411e6c07d2d0fae9e4524082927179654a36/vcr/serialize.py#L13) above and now it's making more sense.

Since all the internal HTTP stuff is happening as bytes, I guess this whole process is kind of backwards.

read bytes -> process bytes -> write bytes -> (yaml doesnt like to write bytes, so decode and then write unicode, which yaml will encode as bytes before sending to disk)

  So yeah, it makes sense to send bytes to serializers, and then we can just have the yaml serializer decode before sending off to the serializer.

**Comment by nickdirienzo** [comment]
Is this still an open issue? 

I bumped to 1.10.0 today then rerecorded a cassette and am seeing string data in Python 3.5.2.
```
 - request:
-    body: !!binary |
-      eyJuYW1lIjogIk15IENhbXBhaWduIiwgInByb2plY3RfaWQiOiAzMjAwMSwgImxhc3RfbW9kaWZp
-      ZWQiOiBudWxsLCAidmlld19pZHMiOiBbODcwMDFdLCAiZWFybGllc3QiOiBudWxsLCAiaG9sZGJh
-      Y2siOiA1MDAsICJwcmltYXJ5X21ldHJpYyI6IHsiaWQiOiA4NzAwMSwgImtpbmQiOiAidmlldyJ9
-      LCAibGF0ZXN0IjogbnVsbCwgInN0YXR1cyI6ICJhY3RpdmUiLCAic2Vjb25kYXJ5X21ldHJpY3Mi
-      OiBbXSwgImlkIjogbnVsbCwgImNoYW5nZXMiOiBudWxsLCAiY3JlYXRlZCI6IG51bGwsICJleHBl
-      cmltZW50X2lkcyI6IFtdLCAicG9saWN5IjogIm9yZGVyZWQifQ==
+    body: '{"primary_metric": {"kind": "view", "id": 37018}, "name": "My Campaign",
+      "project_id": 37009, "policy": "ordered", "id": null, "holdback": 500, "created":
+      null, "secondary_metrics": [], "last_modified": null, "changes": null, "experiment_ids":
+      [], "earliest": null, "latest": null, "status": null, "view_ids": [37018]}'
     headers:
       Accept: ['*/*']
       Accept-Encoding: ['gzip, deflate']
       Connection: [keep-alive]
-      Content-Length: ['322']
+      Content-Length: ['318']
       Content-Type: [application/json]
       User-Agent: [python-requests/2.10.0]
     method: POST
```

**Comment by kevin1024** [comment]
Yup.  Happily merging PRs to fix this :)

**Comment by nickdirienzo** [comment]
I'm trying to best understand the issue at hand. What I'm reading is the serialization pipeline still needs work, but what I'm seeing is a side-effect that was introduced somewhere in one of the recent versions. Is that accurate?

**Comment by kevin1024** [comment]
Yes, one of the recent changes to fix some kind of encoding issue in Python 3 caused this side effect.

**Comment by nickdirienzo** [comment]
Gotcha. Thanks for clarifying, @kevin1024!

**Comment by danilosoares** [comment]
I fix my problem with the following code:

with open(file.path, "rb") as pdf_file:
        encoded_string = base64.b64encode(pdf_file.read())
        req_file = encoded_string.decode('utf-8')

payload = {
      'req_file' : req_file
}

res = requests.post(url, data=json.dumps(payload), headers=headers)

Has work!!!

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
