### ISSUE TITLE
vcrpy replays recently added requests

### ISSUE THREAD

**Issue by Sjord** [kevin1024/vcrpy#245]
After storing a request in the VCR, sometimes vcrpy will replay that request later, even though every request should only be used once.

I made a [little script](https://gist.github.com/Sjord/06bede5fb2702b360413) to reproduce this problem. It starts with an existing YAML file so that `Cassette._rewound` is True. Then when you request the same URL two times, the first request is made to the server and stored, and the second request is replayed. The output looks like this:

```
29e619d8
29e619d8
f59ea0cc
f59ea0cc
da52bd77
da52bd77
760af8e3
760af8e3
34c7af33
34c7af33
```

I would expect every request to hit the server and be stored in the YAML file, and none be replayed. Maybe `Cassette.append` should set the `play_counts` to 1?

**Comment by IvanMalison** [comment]
@Sjord which record mode was used in your test?

**Comment by Sjord** [comment]
@IvanMalison I use `new_episodes`. The script to reproduce this can be found here: 
https://gist.github.com/Sjord/06bede5fb2702b360413

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
