### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by JanLikar** [kevin1024/vcrpy#258]
`test_records_multiple_header_values` and `test_amazon_doctype` are failing with `urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR` and
`requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:646)`, respectively.

**Comment by kevin1024** [comment]
yeah... what's up with that?

**Comment by fxfitz** [comment]
Error 1: `test_records_multiple_header_values` is failing due to a bug in httpbin with flask 0.11 (https://github.com/Runscope/httpbin/issues/290); I've been able to reproduce this with the pytest-httpbin repo and the httpbin repo.  @kevin1024: What would you think about pinning the requirements (probably more appropriate for pytest-httpbin?), and then hooking up the repository to requires.io? From what I've seen, requires.io seems to work pretty well.

Error 2: Still working on figuring out why verification is failing, but I'll probably have something tomorrow.
