### ISSUE TITLE
Add lxml support

### ISSUE THREAD

**Issue by sirex** [kevin1024/vcrpy#285]
lxml can load XML data from URL, when lxml validates XML against schema multiple requests can be made, because XML schemas can import files from URL's.

As far as I know lxml does URL loading from c: `lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:106564)`, not sure if it is possible to patch lxml to make it work with vcr, but it would be nice to have lxml support too.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
