### ISSUE TITLE
Details url for older version of VCR is outdated

### ISSUE THREAD

**Issue by ustroetz** [kevin1024/vcrpy#296]
The link (http://git.io/mHhLBg) reported when a cassette was generated in an older version of VCR is no longer working. 

If you provide me the new one I send a PR to fix it.

https://github.com/kevin1024/vcrpy/blob/ecbc192fc445d3bd91aba43d1a34dd6d9ccb1976/vcr/serialize.py#L30

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
