### ISSUE TITLE
default request matching : order of parameters in URL

### ISSUE THREAD

**Issue by sfranchois** [kevin1024/vcrpy#299]
Hi

For the default URL request matcher, does the order of the query string parameters matter?

During a second run (fetching from cassette), we get a
CannotOverwriteExistingCassetteException
(match_on = ['method', 'query'])

We noticed that the order of parameters in the URI is sometimes different. 
Would vcrpy see these requests as different? 

For example:
http://some_host.com/get_some?a=1&b=2
http://some_host.com/get_some?b=2&a=1

If vcrpy treats these as different URI,do  we need to write a custom request matcher, or can we tell vcrpy to ignore order?

python 3.4.2
vcrpy 1.10.5

Thanks!

Serge Franchosi

**Comment by IvanMalison** [comment]
Check out https://github.com/IvanMalison/okcupyd/blob/46f4eaa9419098f6c299738ce148af55c64deb64/okcupyd_testing/util.py#L149

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
