### ISSUE TITLE
vcr doesn't record requests used within a library?

### ISSUE THREAD

**Issue by meetmangukiya** [kevin1024/vcrpy#316]
I am using github3, and want to test it. This is what I used:
```py
  1 import os
  2 
  3 import vcr
  4 import github3
  5 
  6 @vcr.use_cassette('github.yaml')
  7 def test_github3():
  8     gh = github3.GitHub(token=os.environ.get('GH_TOKEN'))
  9     coala = gh.organization('coala')
```
when I run this test, the cassete is not recorded

`github3` uses a `GitHubSession` session which inherits from `requests.Session` internally

**Comment by georgedorn** [comment]
I discovered a similar problem with the Stripe API client, which uses requests.Session as well.  I suspect vcr doesn't mock this usage properly.

**Comment by IvanMalison** [comment]
@georgedorn yeah request likely does not patch session properly. That should be ticketed.

**Comment by rfadams** [comment]
@meetmangukiya @georgedorn @IvanMalison I had a similar issue, but with a "client" we developed internally that also uses requests. I spent a while trying to diagnose the issue to no avail. What was most frustrating is that since it is an internal client, it is used in another codebase as well and VCRpy was working great over there. 

Finally, I had the idea to downgrade VCRpy in the new codebase to the same version as used in the old codebase and it worked! Here is a screenshot (below) showing a failing test b/c it bypasses VCRpy, I uninstall VCRpy==1.11.1, and re-install VCRpy==1.11.0 - then the test passes!

I tried various different configs and methods of using VCRpy (decorator vs `with`-context) all to no avail, it just wouldn't see the http requests made by the "requests" lib inside the API client. Sorry I don't have more help. 

<img width="1746" alt="image 2017-07-30 at 8 54 16 am public" src="https://user-images.githubusercontent.com/663459/28754975-83651b52-7505-11e7-8290-b399dc671743.png">

**Comment by snebel29** [comment]
I'm having the same issue, vcr not recording calls made by a library which is being call by a method of an object built by me. The library is using requests internally, I just read this thread and downgraded to `1.11.0` but still doesn't work.. I'm not sure if this is the same use case by the way.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by Fatuity** [comment]
I'm using VCR and i'm having a similar problem as described here.
I'm using zeep SOAP client, with requests.Session for transport, and seems like it doesn't intercept HTTP requests.
On the other hand I'm using requests.Session() also for REST HTTP requests and it seems to intercept and record these, is there any solution?
