### ISSUE TITLE
Provide ability to check whether VCR is recording or not

### ISSUE THREAD

**Issue by mattyb** [kevin1024/vcrpy#317]
The ruby client provides this as `VCR.current_cassette.recording?`. This is particularly helpful when you have a method that polls an endpoint. You can have a typical polling interval during recording, but set it to 0 during playback.

**Comment by graingert** [comment]
Code should not depend on test utils. Make your interval or sleep function a  parameter of your unit under test

**Comment by mattyb** [comment]
Not suggesting that the code under test would use the test util. In the test code either the polling interval values can be mocked, or the function parameter can be adjusted, based on whether the cassette is recording or playing back.

**Comment by graingert** [comment]
But the test code would know if it was running under a cassette, it would be inside the decorator or with block

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
