### ISSUE TITLE
Wrong cassette using http.client and tunneled connection

### ISSUE THREAD

**Issue by blacksponge** [kevin1024/vcrpy#322]
Hello,
I am using the `HTTPConnection.set_tunnel` method from `http.client` to get the proxy right but when I want to record a request 
  * the cassette file does not contain any of the request to the proxy (which are actually what I need to test)
  * the URL stored in the cassette is `[proxy host]/path-to-resources` and not `[host I want to reach]/path-to-resources`. 

I can fairly understand that it can be seen as useless to record interaction with the proxy but in that case it would make more sense to not record the proxy host but the real host on which we want to perform the query.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
