### ISSUE TITLE
Compatibility with GRequests?

### ISSUE THREAD

**Issue by ut-adamc** [kevin1024/vcrpy#323]
This is really just a request for clarification. Am I correct in thinking this does not work with GRequests? (When I try running tests, it only seems to record the first request in every batch sent through map.)

Thanks in advance.

**Comment by graingert** [comment]
I'd stick to aiohttp for async http.

**Comment by ut-adamc** [comment]
Alas, that code is already set, so we can't use this to test if it is not compatible.

**Comment by graingert** [comment]
@ut-adamc grequests is only a tiny wrapper around a monkey patched requests. I'd suggest rolling your own then disabling the monkey patches in your tests and running synchronously

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
