### ISSUE TITLE
Add configuration flag to assert all requests were played

### ISSUE THREAD

**Issue by eliasdorneles** [kevin1024/vcrpy#329]
It would be nice to be able to configure VCR to assert that all recorded requests must be played without having to write the assertion explicitly.

The idea is to be able to ensure that all the requests you recorded are indeed being called by the code being exercised by a test: to avoid cases where a test will pass even if the code doesn't do a request that was expected but doesn't have any "assertable" results.

Here is a pattern I've been using in some test code:

    with vcr.use_cassette('some_cassette'):
        ... exercise code here
        self.assertTrue(cassette.dirty or cassette.all_played, "Expected more requests")

The `cassette.dirty` check is needed because when recording, the requests aren't played.

It would be nice to be able to do:

    @vcr.use_cassette(require_all_played=True)
    def test_something
        ... exercise code here

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
