### ISSUE TITLE
Add "no-op" record mode ?

### ISSUE THREAD

**Issue by pakal** [kevin1024/vcrpy#335]
We have a test suite which, when run againts real servers, generates very different HTTP responses (with cookies, E-tags, misc tokens, dates.......).

So it'd be handy to be able to bypass vcr-marked tests when used against live server, so that existing Cassetes are neither used nor overwritten with different responses.

Thus VCR would be used only for sandbox (continuous integration), with "none" record mode, after having been updated once with "all" record mode.

What's your opinion about this evolution ?

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
