### ISSUE TITLE
New Feature: Automatic Re-recording

### ISSUE THREAD

**Issue by jeffnappi** [kevin1024/vcrpy#337]
Automatic re-recording would be a great feature to add to vcrpy. This is a feature that has been available in the [Ruby VCR for quite some time](https://relishapp.com/vcr/vcr/v/3-0-3/docs/cassettes/automatic-re-recording).

I'd be happy to work on the implementation, but I'd like to know there is support for such a feature before I implement it.

**Comment by paultiplady** [comment]
I'd love to see this feature, @kevin1024 is there interest in taking a contribution here?

**Comment by radek-sprta** [comment]
I came to ask the same question. I would happily help testing this, if you wanna have a go at it.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
