### ISSUE TITLE
django 2.0 liveserver/runserver uses HTTP 1.1 and breaks playback

### ISSUE THREAD

**Issue by grigi** [kevin1024/vcrpy#349]
I have a system where I use vcrpy for behave tests through livetestserver, it was working fine until django 2.0 (it was the last issue)
So I decided to debug it, and it seems that the issue was HTTP 1.1 keep-alive pipelining is getting confused, as it would expect the same connection, but sometimes gets a non-open connection.

By applying this monkeypatch to force LiveTestServer/runserver to drop to HTTP 1.0 compliance it all started working again:
```py
from django.core.servers import basehttp
basehttp.ServerHandler.http_version = '1.0'
```

Could you please update the docs to mention the caveat of HTTP 1.1 pipelining and selective playback, and either document the hack or make `with my_vcr.use_cassette()` apply that monkeypatch conditionally?

**Comment by kevin1024** [comment]
Thanks for doing the research.  Would merge a PR that adds that caveat to docs.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
