### ISSUE TITLE
Yaml serializer fails since pyyaml 4.1

### ISSUE THREAD

**Issue by jbagot** [kevin1024/vcrpy#366]
Yesterday pyyaml was updated to version 4.1
And now I'm receiving this error:
`yaml.representer.RepresenterError: ('cannot represent an object', URL('<url>')`
The problem is in the `vcr/serializers/yamlserializer.py` file. 
When the method `serialize` method is called.

I found this pull request that was pushed in the version 4.1 of pyyaml:
https://github.com/yaml/pyyaml/pull/74
 where they change the behaviour `dump`, `Dumper`, `CDumper` and the same with the loaders. Before the update this methods were "danger" and now are "safe" then we can change the line in the serializer to the "danger" version because is exactly the same that we use before this update.
I'll try to fix it later.

**Comment by stefangordon** [comment]
I'm seeing even scarier things with pyyaml 4.1 -- vcrpy is actually overwriting cassettes during test runs (with record mode=once) on pyyaml 4.1

**Comment by lmazuel** [comment]
Got hit by this as well, and the only difference between working Travis and broken Travis is indeed PyYAML 4.1 / 3.12. Thanks for the workaround @stefangordon, I will try to pin my dependency to 3.12 for now, and find time to re-record everything using 4.1 (:cry: :cry: :cry:)

**Comment by lmazuel** [comment]
@stefangordon @jbagot found out the problem.

After some investigation, it impacts only files recorded with Python 2.7. Because starting PyYAML 4.x, the methods “load/safe_load” becomes respectively “danger_load/load” (i.e. by default creating Python object from YAML parsing is disabled).
In Py 2.7, YAML contains this:
```yaml
body: {string: !!python/unicode 'stuff'.....
```

Which will not be parsed anymore by default (since it creates a Python object and [is vulnerable to attack](https://blog.talosintelligence.com/2017/09/vulnerability-spotlight-yaml-remote.html)). 

This means that with PyYAML 3.x series, if a malicious person introduce bad python code in the recordings, each time the recordings are replayed the code is executed (?!?!??). And you see [here](https://github.com/yaml/pyyaml/issues/5#issuecomment-260671692), this could simple as:
```yaml
favorite_activity: !!python/object/apply:os.system ['rm *']
```

I'm not sure if it means that VCRPy is not compatible anymore with Py2.7 if PyYAML is installed, or if this means that PyYAML should be pinned to 3.12 on Py2.7 and >=4.0 on Py3. Or if you just document as PyYAML did that playing recording is vulnerable to attack if PyYAML is < 4.0.

**Comment by mark0978** [comment]
The correct place to pin the version is in setup.py

**Comment by jbagot** [comment]
I never used python2 in the project where I have this problem. I started this issue because with the pyyaml 4.1 doesn't work in my project (python3.6).
Now is using the safe dumper instead of the danger and the pyyaml return an error when it has to represent a URL object.

**Comment by lmazuel** [comment]
@jbagot In my scenario (which is clearly different than yours), a simple replace like `s$!!python/unicode $$` was enough to make my old recordings work with all PyYAML versions. But I guess it also depends on the pre-processors used and options.

I think the idea is that for each `!!python/xxxx` in the YAML file, this won't work out-of-the-box. VCRPy should probably propose a safe/danger mode telling about the issue and give the hot potato to the VCRPy user to decide. If you control the recordings, "danger" mode is great and allow you to use Python objects, but if you don't (like accepting PR on an OpenSource project with recordings you didn't do), safe mode should be enforced.

**Comment by sevein** [comment]
It seems that PyYAML 4.1 has been removed. PyYAML 3.12 is again the latest stable release (which may bring some vcrpy users to the previous state) but I guess that won't be the case as soon as PyYAML 4.2 is released which seems like it's already in progress with a 4.2b1 release already published in PyPI: https://pypi.org/project/PyYAML/#history.

**Comment by lamenezes** [comment]
I think we have to wait and see this new release of PyYAML to work on a fix to this issue. From the commentaries here using pyyaml < 4 works fine, so pinning the version is the solution for now.

**Comment by lamenezes** [comment]
I believe this was fixed by PyYAML. If the problem persists feel free to open another issue. Thanks everyone for the discussion :)
