### ISSUE TITLE
Add vcr to repository topics

### ISSUE THREAD

**Issue by abitrolly** [kevin1024/vcrpy#377]
Because. https://github.com/topics/vcr

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by abitrolly** [comment]
@neozenith no need to open a new ticket. Just adding a tag is easier than replying to this message i web UI. )
