### ISSUE TITLE
Do not download body using requests stream=True

### ISSUE THREAD

**Issue by sd4B75bJ** [kevin1024/vcrpy#378]
I'm trying to just check the content-length without downloading the body. I can't use a HEAD request as the server only excepts GETs and content-length is not always included anyway. Thus I am using a GET request with stream=True and then closing the connection
```python
with requests.get(self.url, stream=True) as r:
     return int(r.headers['content-length'])
```
However with vcrpy the body is being downloaded and stored in the cassette, how can I avoide this? Ideally I would avoide this instead of filtering out the body after the fact as the files I am downloading are around 60GB

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
