### ISSUE TITLE
vcr use_cassette does not work for 400 status code for aiohttp

### ISSUE THREAD

**Issue by kasirajanss93** [kevin1024/vcrpy#380]
Seems like @vcr.use_cassette does not record and creates an yaml file when running test using aiohttp

It hits the server each time rather than recording and using the yaml file for reply.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
