### ISSUE TITLE
Small potential improvement in auto naming

### ISSUE THREAD

**Issue by pedropregueiro** [kevin1024/vcrpy#381]
I'm using VCR.py for some integration mocking, one of them being Stripe, and I was considering using the [auto-naming](https://vcrpy.readthedocs.io/en/latest/advanced.html#automatic-cassette-naming) functionality for this, but then I noticed that if I use that, I can't really control the folder structure of my cassettes. Maybe this is a bit picky or it actually could be done some other way (like using the path_transformer), but I reckon it could useful to allow for the usage below and still do the auto-naming.

For example, this piece of code would generate a file `fixtures/cassettes/stripe/my_test.json`:
```
import vcr

my_vcr = vcr.VCR(
    serializer='json',
    cassette_library_dir='fixtures/cassettes',
    path_transformer=vcr.VCR.ensure_suffix('.json'),
)

@my_vcr.use_cassette('stripe/'):
def my_test():
  ...
```

Or should I then have a different VCR object per integration with a different `cassette_library_dir`?

P.S. - thanks for an aweome tool! 👏

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
