### ISSUE TITLE
boto3 integration broken

### ISSUE THREAD

**Issue by AnalogJ** [kevin1024/vcrpy#382]
Hey,
I've recently started seeing boto3 related failures in my unit tests. The recordings had been working previously, but it seems that something has changed in boto, and the vcrpy support is no longer working. 

```
------------------------------------------------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------------------------------------------------
/Users/analogj/repos/lexicon/venv/lib/python2.7/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```

**Comment by adamchainz** [comment]
I'm also seeing problems with boto3 1.8+ / botocore 1.11+ - probably due to [stopping use of vendorede requests/urllib3](https://botocore.amazonaws.com/v1/documentation/api/latest/index.html#upgrading-to-1-11-0). But that warning you're seeing doesn't seem related to what I am seeing, which is just that boto3 functions continued to attempt actual API calls.

**Comment by jeshan** [comment]
I'm seeing that when switching from latest 1.7.x (1.7.84) to next release (1.8.0), vcr.py has stopped saving cassette.

**Comment by jeshan** [comment]
I've posted a bounty for whoever wants to fix this!
https://www.bountysource.com/issues/62777063-boto3-integration-broken

**Comment by HeroPD** [comment]
Seems S3 root cert missing from aws_ca_bundle in boto3
This warning not related to vcrpy but u can solve it by
`pip install certifi`

to find cert location do below

```
>>> import certifi
>>> certifi.where()
'/usr/local/lib/python2.7/site-packages/certifi/cacert.pem'
```

set cert location to environment variable $AWS_CA_BUNDLE
`export AWS_CA_BUNDLE=/usr/local/lib/python2.7/site-packages/certifi/cacert.pem`

**Comment by 1oglop1** [comment]
@HeroPD This workaround did not help me. 
vcr cassete still does not contain any recordings and warning is still there.

**Comment by jeshan** [comment]
@1oglop1 he was only writing about making a warning go away, not fix this issue

**Comment by svdgraaf** [comment]
Is there any news on this PR? I tried and debugged the branch, but it seems my boto3 calls are still skipped, not sure why yet.

> boto3==1.9.165
> botocore==1.12.165

@1oglop1 thanks for adding the debug logs, that helps a lot for logic analysis :)

If I can be of any help on this issue, I'd be glad to help out! Until then, I'll continue my struggles :)

**Comment by 1oglop1** [comment]
@svdgraaf Check my PR #411 I have a branch working with boto3, however tests fails for legacy python :/

**Comment by neozenith** [comment]
Ok I'm trying to catch up on this issue so we can close it out.

| Author | PR | Status
| --- | --- | --- |
| @1oglop1 | https://github.com/kevin1024/vcrpy/pull/411 | Needs AWS credentials |
| @arthurHamon2 |  https://github.com/kevin1024/vcrpy/pull/448 |  `boto3` is an allowed_failure in `.travis.yml` |

I had a look at the tests in #411 and it looks like it just needs credentials to connect to IAM to verify a `vcrpy` user exists.

Does it have to be an actual AWS account? Or could this be stubbed out? 

Asking out of curiosity as I'm not sure what the best answer is here on how to test this. It seems like we are testing AWS more than patching boto3.

**Comment by 1oglop1** [comment]
@neozenith 
Lemme give you little more insight.

### History:

There was a `boto3` integration which broke long time ago and probably for that reason `boto3` tests were allowed to fail or any other reason.
This solution needed AWS creds as well, which were probably stored inside `secure:` of `travis.yml`.
But after I tried to use boto3 integration, I found out that it did not work at all.

### When I started to work on the issue:

I managed to fix the integration and created new tests agains IAM.
Because previous integration relied on S3 API which can cost money, where IAM API does not.

 ### When @arthurHamon2 joined to the battle

Almost all of my tests were passing however, it turned out that I managed to break compatibility with legacy python and its tests were failing. 
So I raised #434.
This is what @arthurHamon2 managed to fix and raised #448.

### Present

However all of this came little too late and @arthurHamon2 did not notice that `boto3` tests are failing (because they were still `allow_failure`, inherited from the master)
 
I tried to merge the master to my branch and see what's wrong (you can find latest details in #411)
Decided to remove `boto3` from `allow_failure` for better visibility in pipeline.

Unfortunately I do not have time to play with this issue anymore in my spare time but I can still provide AWS credentials. And I added @arthurHamon2 as a contributor to my fork, so he can work on issue there.

Once technical issues are resolved we can have a discussion about AWS credentials. I believe this should not be a problem since we are using free endpoints. 


### Technical things

> Does it have to be an actual AWS account? Or could this be stubbed out?

I tried to use `moto` however it did not work due to nature of `vcrpy` and how it spoofs the data from the request.
So I'd say there is no simple way to mock this, unless there is a solution running the server.
However there is a chance that `vcrpy` could make use of https://github.com/localstack/localstack which could satisfy the technical needs.

>Regarding your comments at #448
I mostly agree with your suggestions, I left `test_boto3_without_vcr` there because I was not sure what was the original intention.

**Comment by neozenith** [comment]
So very happy to see this closed!!

**Comment by svdgraaf** [comment]
Same here! Thanks for everyone involved! 👏
