### ISSUE TITLE
[idea] templated cassettes

### ISSUE THREAD

**Issue by MikeWooster** [kevin1024/vcrpy#383]
Firstly, I would like to say how great vcrpy is.  It has definitely made testing so much easier!

I have frequently found myself needing to customise the response in the vcrpy cassette.  To do this, I have had to write a templated cassette, save that to a temporary location and then point vcrpy to that so that it responds with the custom response.  I wondered if it would be (or already is) possible to either load a cassette by passing in a string, or to integrate vcrpy with something like jinja templates so that we can customise the response within the library itself?

My preferred approach would be the latter, as it would make the tests more readable.  I was thinking it could look something like:
```
with vcr.use_cassette('fixtures/vcr_cassettes/postcode_lookup.yaml', context={'latitude': '0.629834'}) as cass:
    response = urllib2.urlopen('http://www.get_postcode.com/OX49 5NU/').read()
    assert address.latitude == 0.629834
```

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
