### ISSUE TITLE
before_record_request mutates request

### ISSUE THREAD

**Issue by aqw** [kevin1024/vcrpy#387]
I have run into the same problem as #356, but instead with the request. Using filters does not mutate the request, but using the before_record_request callback does modify the request.

I would provide a patch (as the fix is trivial), but I can't quite figure out how to test this using httplib (which is what the tests use). Unlike the requests package, I can't find in the httplib API where the request headers would be stored.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
