### ISSUE TITLE
Tell between recorded and real response without logging

### ISSUE THREAD

**Issue by deeplook** [kevin1024/vcrpy#394]
It seems like the only way to tell if a request response actually comes from a cassette or is a real, _fresh_ response of some API is to use the logging mechanism described for debugging here: https://vcrpy.readthedocs.io/en/latest/debugging.html. It would be helpful to have a simpler way without involving the logging machinery, maybe by writing a flag into `vcr.VCR` objects.

**Comment by deeplook** [comment]
Well, something like this might work. Is this the recommended way?

```python
import vcr
from vcr.cassette import Cassette
from vcr.request import Request

path = 'headers.yml'

# execute one request, record response
with vcr.use_cassette(path):
    resp = requests.get('http://httpbin.org/headers')

# test if some request has been recorded 
req = Request('GET', 'http://httpbin.org/headers', 'irrelevant body?', {'foo': 'not checked'})
assert Cassette(None).load(path=path).can_play_response_for(req) == True
assert req in Cassette(None).load(path=path)
```

**Comment by vEpiphyte** [comment]
aiohttp stub does not log playback of of recorded responses

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
