### ISSUE TITLE
Determine if request is currently being recoreded. 

### ISSUE THREAD

**Issue by facetoe** [kevin1024/vcrpy#410]
Hi, 

I'm wondering if there is a supported way of determining whether a particular interaction is being recorded or replayed? The only way I've found is to run `len(cassette)` in the context manager and if the value is zero then I assume we are recording. Is there a better way?

Thanks for the great library!

**Comment by 1oglop1** [comment]
From what I could understand request is recorder if `vcr.request.Request` run successfully. 
As for the `len(cassete)`
if `len(cassete) == 0` no requests are recorded and file won't be saved
so to determine if you have and requests correctly executed `len(cassete)` must be high the `0`

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale and we have a lot of old tickets that need to be groomed, I'm closing this for now to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏
