### ISSUE TITLE
Python2.7 and Python3.6 bytearray printing object path in cassette body

### ISSUE THREAD

**Issue by mwaldt** [kevin1024/vcrpy#422]
This came up while maintaining a package that requires python 2 and python 3 support. When submitting a `bytearray` over a request my tox tests were failing. I was able to debug this down the the following:
```# python 3
interactions:
- request:
    body: !!python/object/apply:builtins.bytearray``` 
```# python 2
interactions:
- request:
    body: !!python/object/apply:__builtin__.bytearray```

The path to the python objects is different between the python version which was causing tests to fail with `record_mode="none"`.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale, would you mind closing it if it is no longer needed / relevant?

If I haven't heard anything in a week I'll mark it as closed as we have a lot of old tickets that need to be groomed to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by mwaldt** [comment]
Considering python 2.7 support is depreciated officially this can just be closed.
