### ISSUE TITLE
Newline at the end of JSON files

### ISSUE THREAD

**Issue by michellelynne** [kevin1024/vcrpy#429]
Cassettes created as JSON do not have a newline at the end. Right now, I manually add it before commiting.

**Comment by michellelynne** [comment]
I'd like to take this issue myself, but not sure if it will be valid since it's just style. Thoughts?

**Comment by IvanMalison** [comment]
@michellelynne ending files with a newline is a good idea. e.g. cat doesn't work properly if they don't.

We would happily accept a pull request for this.

**Comment by neozenith** [comment]
A lot of changes have happened to VCRpy since this ticket was opened. As this ticket has become stale, would you mind closing it if it is no longer needed / relevant?

If I haven't heard anything in a week I'll mark it as closed as we have a lot of old tickets that need to be groomed to make it easier to see what is still relevant.

However if it is still needed, please feel free to re-open or create a new ticket.

Thanks! 🙏

**Comment by AaronRobson** [comment]
I'll pick this up shortly.

**Comment by AaronRobson** [comment]
Please see PR for a fix and test.

Do the other formats like yaml have the same issue?

**Comment by AaronRobson** [comment]
@IvanMalison I don't suppose you'd merge the PR for us would you?

**Comment by neozenith** [comment]
Hi, I just wanted to update active PRs and issues to let you know I will no longer be an active maintainer on this project.

I recently changed jobs where I no longer use VCRpy or Python at all so I don't have the bandwidth anymore. I won't be monitoring issues or PRs either.

I will have to delegate to other maintainers or ask for some contributors to step up.

I know the Azure CLI uses VCRpy so it would be nice if they could spare some sprint time to maintain this project as it was invaluable in our CI when I was using it.

Kind regards,
Josh

**Comment by neozenith** [comment]
@arthurHamon2  this could be a quick win release?
