### ISSUE TITLE
Use codetriage.com or something similar

### ISSUE THREAD

**Issue by IvanMalison** [kevin1024/vcrpy#452]
Though @kevin1024 has added a pretty crazy number of maintainers over the last couple of years, I don't really think that we (obviously myself included) are doing all that great a job of responding to issues/pull requests on this repository.

I was just looking through issues/pull request on the repo, and was pretty surprised to see that a fair number of the issues/prs that have been made over the past few months have received no response.

I still subscribe to notifications on this repo, but I basically zone them out because there are just too many of them for me to be able to go through them all. I'd be much more willing to help out if there were a well defined subset of the issues that I was "responsible for" in some way.

I've seen some repositories using codetriage.com to deal with this sort of thing, but I'm not really familiar with it. Thoughts?

**Comment by kevin1024** [comment]
Haven’t heard of codetriage but if it could help then it seems worth trying.  I really appreciate the time you and the other maintainers have put into VCR!

**Comment by neozenith** [comment]
Sounds good. We can give it a try and if in 3-6 months it isn’t working out we can disable the integration. 

I heard GitHub is trying to ramp up NLP tooling to help semi-automate some of these tasks.

**Comment by neozenith** [comment]
I have pinned the following issue and locked conversation to only collaborators.

https://github.com/kevin1024/vcrpy/issues/469

Essentially there is a call to action for anyone that want to help with the _triage and fix_ pipeline.

There are too many libraries for anyone to reasonably consider maintaining all of it.

I have been trying to at least label issues with their library name as a tag, and if it is a `bug` or `enhancement`.

Then an issue goes through these stages:
 - `help required replicating`
 - `verified can replicate`

We have had a couple `aiohttp` issues because they were marked `verified can replicate` and someone picked up the example and opened a PR which we closed out.

If we can get people to help actively triage and label that'd be a great start.

I have a release candidate for v4.0 which incorporates HugoVK's PR to cull legacy python and add support for py38. After that I'll roll through closing issues that have had birthday's, asking users to upgrade and open a new issue if it is still relevant.

We only have 12 open issues from 2019. The remainder (~65 at time of writing) are from 2018 or earlier.

In fact @kevin1024 and @IvanMalison would you mind closing out some old ones from 2015 if they aren't relevant anymore?

https://github.com/kevin1024/vcrpy/issues?q=is%3Aissue+is%3Aopen+sort%3Acreated-asc

I'm going to close this issue though as it look like no interest to pursue it for it now.
