### ISSUE TITLE
stacking cassette contexts ?

### ISSUE THREAD

**Issue by asmodehn** [kevin1024/vcrpy#487]
Hi,
I have been using vcrpy for tests for a little while, and recently I had an attempt at stacking cassette contexts. Something like : 
```py
import asyncio
import aiohttp
import vcr
import logging

logging.basicConfig()  # you need to initialize logging, otherwise you will not see anything from vcrpy
vcr_log = logging.getLogger("vcr")
vcr_log.setLevel(logging.INFO)


async def httpbin_get():
    async with aiohttp.ClientSession() as session:
        with vcr.use_cassette('get_outer.yml', record_mode='all'):  # want to record any traffic, for error debugging purposes...
            with vcr.use_cassette('get_inner.yml', record_mode='once'):  # recorded interraction once. replay during tests.
                async with session.get('http://httpbin.org/get') as resp:
                    print(resp.status)
                    print(await resp.text())

loop = asyncio.get_event_loop()
loop.run_until_complete(httpbin_get())

```

This gave me : 
```
 python k7test.py 
INFO:vcr.cassette:<function VCR._build_before_record_request.<locals>.before_record_request at 0x7fa666dc3d08>
INFO:vcr.cassette:<function VCR._build_before_record_request.<locals>.before_record_request at 0x7fa666ddfb70>
INFO:vcr.cassette:Appending request <Request (GET) http://httpbin.org/get> and response {'body': {'string': b'{\n  "args": {}, \n  "headers": {\n    "Accept": "*/*", \n    "Accept-Encoding": "gzip, deflate", \n    "Host": "httpbin.org", \n    "User-Agent": "Python/3.7 aiohttp/4.0.0a1"\n  }, \n  "origin": "78.193.44.54, 78.193.44.54", \n  "url": "https://httpbin.org/get"\n}\n'}, 'headers': {'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Connection': 'keep-alive', 'Content-Encoding': 'gzip', 'Content-Length': '185', 'Content-Type': 'application/json', 'Date': 'Thu, 31 Oct 2019 09:33:32 GMT', 'Referrer-Policy': 'no-referrer-when-downgrade', 'Server': 'nginx', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block'}, 'status': {'code': 200, 'message': 'OK'}, 'url': 'http://httpbin.org/get'}
200
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Host": "httpbin.org", 
    "User-Agent": "Python/3.7 aiohttp/4.0.0a1"
  }, 
  "origin": "78.193.44.54, 78.193.44.54", 
  "url": "https://httpbin.org/get"
}
```
along with a cassette yaml : `get_inner.yml`

What happened to the outer one ?
I would assume that, for subsequent run, the inner_get will get replayed, but I ll never get the record of it in the outer ?
Is that behaviour expected?

I am using vcr for tests (via https://github.com/kiwicom/pytest-recording), to record traffic and replay it as I am testing in CI.
And I am planning to use vcr as well, in code, to record any traffic from my HTTP client, in case an error happens, so that a user can easily access the data received just before the crash (a likely culprit for that crash).

Currently these two implementations currently interfere in my tests as my simple example above demonstrate.
But maybe I am holding this the wrong way, and there is another way to implement a "double recording" feature properly ?
Thanks for any hint.

**Comment by neozenith** [comment]
@asmodehn thanks for the question.

I'll qualify that I've only recently started volunteering time on maintenance on this library since August 2019.

That behavior makes sense with what you are seeing and from what I understand of the code.

When you start a `with vcr.use_cassette` context manager `vcr` attempts to import the 6 supported  HTTP libraries and then patch them with the VCR implementations. Ending the context manager unpatches them.

This patching applies in a _global_ sort of way so that it catches any deeply nested calls inside functions that are trying to hit the network so it won't let any requests pass through to the outer context since the inner patch is the most recent.

I see what you are trying to do and it is an interesting use case. Just like having separate loggers to separate out streams of log records, you are trying to separate streams of requests.

Have you seen this part of the documentation?
https://vcrpy.readthedocs.io/en/latest/advanced.html#ignore-requests

I'm not sure if it would work but it allows certain requests to ignore the patched version of aiohttp then fall through to the underlying aiohttp.

This _might_ mean ignored inner requests fall through to the outer patched aiohttp instead.

VCR allows for custom patchers, matchers and persisters too. Where the documentation is lacking, sadly the next step is to read the source code. I'm happy to try and interpret parts of the code if you post links to any of it that seems obscure (and lot of it is).

I hope that helps. But I think you are running up against the bounds of the intended use cases of VCRpy and you might want to consider forking it as a starting point for patching and modifying it to better suit your needs.

**Comment by asmodehn** [comment]
Thanks a lot for the explanation @neozenith ... If the patches are global, then the behaviour I m experiencing makes total sense.
I guess I ll have to find out a way to implement both of the features I am interested in, in a way that work around that limitation... It seems I cannot have the double recording, but maybe I can change my requirements a little to have some kind of "selective" recording depending on the usecase...
I ll dive into the source code to see what I can find.

I'll post here if I manage to get something working...

**Comment by neozenith** [comment]
Thanks. I'll close this issue for now as we have addressed the behaviour is as expected.

But please comment back here for follow up as a form of documentation.
